Features/profil
supercrocman/L1_ALT_CLONE_YOUTUBE pull request #26
Opened 2023-05-02 14:16 UTC by esemedo

connexion et inscription

2023-05-03 09:31 UTC, DevMehd requested changes

2023-05-03 09:31 UTC, DevMehd commented on frontend/src/components/profil/components/Signup.js
> +                    className={`${profilStyles.profilContainer}`}
Pourquoi mettre des `accents` pour une juste une variable ?

2023-05-03 09:31 UTC, DevMehd commented on frontend/src/components/profil/components/Signup.js
> +                    className={`${profilStyles.lien}`}
Pourquoi mettre des `accents` pour une juste une variable ?

2023-05-03 09:31 UTC, DevMehd commented on frontend/src/pages/api/hello.js
A quoi ça sert ?

2023-05-03 09:31 UTC, DevMehd commented on frontend/src/pages/confirm/[confirmation].js
> +            <Box className={`${profilStyles.profilContainer}`}>
Pourquoi mettre des `accents` pour une juste une variable ?

2023-05-03 09:31 UTC, DevMehd commented on frontend/src/pages/confirm/[confirmation].js
> +                    className={`${profilStyles.profilContainer}`}
Pourquoi mettre des `accents` pour une juste une variable ?

2023-05-03 09:31 UTC, DevMehd commented on yarn.lock
Ne doit pas exister

2023-05-03 09:31 UTC, DevMehd commented on package.json
Ne doit pas exister

2023-05-03 09:47 UTC, DevMehd commented on backend/middlewares/profil.js
> +                                "L'utilisateur a été crée. Aller checker vos mails",
L'utilisateur a été créé. Allez vérifier vos e-mails. même

2023-05-03 14:13 UTC, DevMehd approved these changes

2023-05-03 20:35 UTC, DevMehd commented on frontend/src/components/AccountMenu.js
> +                            <Avatar src={user.avatar ? user.avatar : null}>
Tu n'utilise pas le stringToColor ici ?

2023-05-03 20:35 UTC, DevMehd commented on frontend/src/components/AccountMenu.js
> +                        <Avatar src={user.avatar ? user.avatar : null}>
Ici aussi ?

2023-05-04 06:21 UTC, supercrocman requested changes

2023-05-04 06:21 UTC, supercrocman commented on backend/middlewares/profil.js
> +                ...req.body,
⚠️ faille de sécurité

2023-05-04 06:21 UTC, supercrocman commented on frontend/src/components/profil/components/Signup.js
> +            formData.append('banned', 0);
⚠️ Faille de sécurité

2023-05-04 12:17 UTC, merged